# Generated by Django 6.1.1 on 2026-09-12 09:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('patients', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency_original', models.CharField(choices=[('USD', 'Dollar ($)'), ('FC', 'Franc congolais (FC)')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Taux utilisé')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Montant ($)')),
                ('sessions_prescribed', models.PositiveIntegerField(default=1, verbose_name='Séances prescrites')),
                ('sessions_done', models.PositiveIntegerField(default=0, verbose_name='Séances effectuées')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('doctor_amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('center_amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('observation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_care_treatments', to='settings_app.staff', verbose_name='Médecin traitant')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_care_services', to='finance.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_care_services', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
