# Generated by Django 6.1.1 on 2026-09-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('home_care', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecareservice',
            name='amount_original',
        ),
        migrations.RemoveField(
            model_name='homecareservice',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='homecareservice',
            name='center_amount_usd',
        ),
        migrations.RemoveField(
            model_name='homecareservice',
            name='currency_original',
        ),
        migrations.RemoveField(
            model_name='homecareservice',
            name='doctor_amount_usd',
        ),
        migrations.RemoveField(
            model_name='homecareservice',
            name='rate_used',
        ),
        migrations.CreateModel(
            name='HomeCarePaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor_amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('center_amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_care_split', to='finance.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
