# Generated by Django 6.1.1 on 2026-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix ($)')),
                ('price_fc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix (FC)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motif', models.CharField(choices=[('KINE', 'Séance kiné'), ('CONSULTATION', 'Consultation'), ('EVALUATION', 'Évaluation'), ('LABORATORY', 'Laboratoire'), ('OTHER', 'Autre')], default='KINE', max_length=20)),
                ('motif_other', models.CharField(blank=True, max_length=150, verbose_name='Précision (autre)')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planifiée'), ('DONE', 'Effectuée'), ('CANCELLED', 'Annulée')], default='DONE', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
