# Generated by Django 6.1.1 on 2026-09-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        ('patients', '0001_initial'),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='session',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='settings_app.staff', verbose_name='Professionnel'),
        ),
        migrations.AddField(
            model_name='session',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='centre.service'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['patient', '-date'], name='centre_sess_patient_963d36_idx'),
        ),
    ]
