# Generated by Django 6.1.1 on 2026-09-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcode',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur système'), ('DIRECTOR', 'Directeur'), ('MANAGER', 'Gestionnaire'), ('ASSISTANT_MANAGER', 'Assistant manager'), ('DOCTOR', 'Médecin'), ('LAB_TECH', 'Technicien de laboratoire'), ('PHARMACIST', 'Pharmacien'), ('PHYSIOTHERAPIST', 'Kinésithérapeute'), ('STAFF', 'Personnel autorisé')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur système'), ('DIRECTOR', 'Directeur'), ('MANAGER', 'Gestionnaire'), ('ASSISTANT_MANAGER', 'Assistant manager'), ('DOCTOR', 'Médecin'), ('LAB_TECH', 'Technicien de laboratoire'), ('PHARMACIST', 'Pharmacien'), ('PHYSIOTHERAPIST', 'Kinésithérapeute'), ('STAFF', 'Personnel autorisé')], default='STAFF', max_length=30),
        ),
    ]
