# Generated by Django 6.1.1 on 2026-09-12 09:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency_original', models.CharField(choices=[('USD', 'Dollar ($)'), ('FC', 'Franc congolais (FC)')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Taux utilisé')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Montant ($)')),
                ('label', models.CharField(max_length=150, verbose_name='Libellé')),
                ('person_other', models.CharField(blank=True, max_length=100, verbose_name='Autre personne')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('observation', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings_app.staff', verbose_name='Personne concernée')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency_original', models.CharField(choices=[('USD', 'Dollar ($)'), ('FC', 'Franc congolais (FC)')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Taux utilisé')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Montant ($)')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True)),
                ('label', models.CharField(max_length=255, verbose_name='Libellé')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('PARTIALLY_PAID', 'Partiellement payée'), ('PAID', 'Soldée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant initial ($)')),
                ('remaining_usd', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Reste dû ($)')),
                ('status', models.CharField(choices=[('OPEN', 'En cours'), ('SETTLED', 'Soldée'), ('WAIVED', 'Abandonnée')], default='OPEN', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='patients.patient')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt', to='finance.invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant')),
                ('currency_original', models.CharField(choices=[('USD', 'Dollar ($)'), ('FC', 'Franc congolais (FC)')], default='USD', max_length=3)),
                ('rate_used', models.DecimalField(decimal_places=4, editable=False, max_digits=12, verbose_name='Taux utilisé')),
                ('amount_usd', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='Montant ($)')),
                ('method', models.CharField(choices=[('CASH', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Virement bancaire')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('VALID', 'Valide'), ('CANCELLED', 'Annulé')], default='VALID', max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payments', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
