# Generated by Django 6.1.1 on 2026-09-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryrecord',
            name='prescriber_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prescripteur (nom libre)'),
        ),
    ]
