# Generated by Django 6.1.1 on 2026-09-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinerecord',
            name='prestation_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Précision (autre prestation)'),
        ),
        migrations.AlterField(
            model_name='medicinerecord',
            name='category',
            field=models.CharField(choices=[('GENERAL_CONSULTATION', 'Médecine générale — Consultation'), ('GENERAL_OTHER', 'Médecine générale — Autre prestation'), ('MANUAL', 'Médecine manuelle'), ('MANUAL_OTHER', 'Médecine manuelle — Autre prestation')], max_length=30),
        ),
    ]
