# Generated by Django 6.1.1 on 2026-09-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_seed_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineSplitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('GENERAL_CONSULTATION', 'Consultation'), ('GENERAL_OTHER', 'Autre prestation'), ('MANUAL', 'Médecine manuelle')], max_length=30)),
                ('prescriber_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('center_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-effective_from'],
            },
        ),
    ]
