# Generated by Django 6.1.1 on 2026-09-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0003_medicinesplitconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinesplitconfig',
            name='category',
            field=models.CharField(choices=[('GENERAL_CONSULTATION', 'Médecine générale — Consultation'), ('GENERAL_OTHER', 'Médecine générale — Autre prestation'), ('MANUAL', 'Médecine manuelle'), ('MANUAL_OTHER', 'Médecine manuelle — Autre prestation')], max_length=30),
        ),
    ]
