# Generated by Django 6.1.1 on 2026-09-12 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Post-nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('birth_place', models.CharField(blank=True, max_length=100, verbose_name='Lieu de naissance')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('day_pattern', models.CharField(choices=[('EVEN', 'Jours pairs'), ('ODD', 'Jours impairs'), ('ALL', 'Tous les jours')], default='ALL', max_length=10, verbose_name='Jour de venue')),
                ('sessions_prescribed', models.PositiveIntegerField(default=0, verbose_name='Séances prescrites')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='settings_app.company', verbose_name='Entreprise')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'middle_name', 'first_name'], name='patients_pa_last_na_96f613_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx')],
            },
        ),
    ]
