# Generated by Django 6.1.1 on 2026-09-12 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Échec de connexion'), ('LOGOUT', 'Déconnexion'), ('EXPORT', 'Export'), ('APPROVE', 'Approbation'), ('CANCEL', 'Annulation')], max_length=20)),
                ('module', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'Succès'), ('FAILURE', 'Échec')], default='SUCCESS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
