# Generated by Django 6.1.1 on 2026-09-12 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motif', models.CharField(max_length=255, verbose_name='Motif du rendez-vous')),
                ('datetime', models.DateTimeField(verbose_name='Date et heure')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Programmé'), ('CONFIRMED', 'Confirmé'), ('DONE', 'Honoré'), ('CANCELLED', 'Annulé'), ('NO_SHOW', 'Absent')], default='SCHEDULED', max_length=10)),
                ('remind_days_before', models.PositiveSmallIntegerField(default=1, verbose_name='Rappel (jours avant)')),
                ('alarm', models.BooleanField(default=True, verbose_name='Alarme activée')),
                ('reminded_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Rappel envoyé le')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='settings_app.staff', verbose_name='Professionnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ['datetime'],
                'indexes': [models.Index(fields=['datetime', 'status'], name='appointment_datetim_c4d2fb_idx')],
            },
        ),
    ]
